replicaCount: 2

image:
  repository: monolithacrdevweu.azurecr.io/simple-app
  pullPolicy: IfNotPresent
  tag: "v1.0"

imagePullSecrets: []
nameOverride: "simple-app"
fullnameOverride: "simple-app"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000
  runAsUser: 1000
  runAsGroup: 3000
  runAsNonRoot: true

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true
   allowPrivilegeEscalation: false

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'

ingress:
  enabled: false
  hosts: []
  tls: []

autoscaling:
  enabled: false

resources: {}

nodeSelector:
  serviceType: app

tolerations: []

affinity: {}
